### ISSUE TITLE
JSON generator not working

### ISSUE THREAD

**Issue by jonatan-ivanov** [fzaninotto/CodeFlower#1]
JSON generator is not working on http://redotheweb.com/CodeFlower/  well. If I generate metrics with the newest windows version (1.56) version of cloc, the output will be only the root element. Examples (symfony-master) neither works.

**Comment by fzaninotto** [comment]
I have cloc 1.56 and I used it on symfony-master successfully. 

Could you please paste the process you followed, and the result of each step ?

**Comment by jonatan-ivanov** [comment]
Sure:
1. Download https://nodeload.github.com/symfony/symfony/tar.gz/master
2. Extract
3. Run cloc:
   c:\Documents and Settings\jivanov\Desktop>cloc symfony-master --csv --by-file --report-file=symfony.cloc
       2804 text files.
       2731 unique files.
       1197 files ignored.
   Wrote symfony.cloc
   c:\Documents and Settings\jivanov\Desktop>
4. Paste the whole content of symfony.cloc into the generator then press convert:
   {"name":"root","size":2188,"language":"XSD"}

**Comment by fzaninotto** [comment]
Could you paste the contents of the `symfony.cloc` file?

**Comment by jonatan-ivanov** [comment]
Yepp, http://pastebin.com/v8nADSJE

**Comment by jonatan-ivanov** [comment]
Thanks!
