### ISSUE TITLE
more complex flowers?

### ISSUE THREAD

**Issue by jonathanlocke** [fzaninotto/CodeFlower#16]
would be interesting to measure code in other ways than just LOC and allow these measures to affect both the size and color of flower petals. for example, metrics like:
- methods per class
- average lines per method
- cyclomatic complexity
- test coverage

rather than taking on all these things directly, perhaps codeflower could simply provide a slight extension to the json data format that allows integration with arbitrary tools by tagging values with metric type as well as value. For example { metric="loc" value="500" } or { metric="averageMethodLines" value="1.5" }. codeflower might have to perform some range scaling on values but other projects could handle the data extraction (it would be neat, btw, if that could be more seamless and automatic... ideally someone could add a codeflower to their git project that continuously updates all kinds of metrics in just a few minutes... perhaps codeflower should be integrated into github...).

i wonder if there might not be a kind of biology/morphology to codeflowers where you can recognize different "species" of projects using additional metrics like these...

**Comment by fzaninotto** [comment]
You should definitely test these options and see if patterns emerge. I found interesting patterns with files and LOC (cf http://www.redotheweb.com/2013/03/04/visual-patterns-in-source-code-arrangement.html), there are patterns in other dimensions.
