### ISSUE TITLE
Middle nodes not being shown

### ISSUE THREAD

**Issue by monitsingh** [fzaninotto/CodeFlower#20]
In my final diagram, not all nodes are shown and the final diagram shows the links starting from nowhere. However, if i collapse my first node then the middle nodes for the next two parent nodes appear, if i collapse second parent node, fourth one appears and so on. Unfortunately, not able to figure out the cause of the issue.

![image](https://cloud.githubusercontent.com/assets/13075884/12704847/4855d870-c864-11e5-9266-e615ccbb868b.png)

**Comment by fzaninotto** [comment]
You've done some tweaking with the code, I really don't see how I could help you there.
