### ISSUE TITLE
Faster rendering?

### ISSUE THREAD

**Issue by GeekTieGuy** [fzaninotto/CodeFlower#33]
When visualizing extremely large codebases, it takes 10's of minutes to render a code flower. I'm interested in working on a way to change that, but I'm not sure where to start. I've looked a bit at this: https://bl.ocks.org/Kcnarf/6a0b4488bc60ea61eb887bf4d1f9b2b5, but I can't see how to apply the technique there to CodeFlower.

**Comment by fzaninotto** [comment]
Sorry, I can't offer you support on d3.js. Feel free to experiment and report your findings here.

**Comment by GeekTieGuy** [comment]
Yeah, I almost figured as much. Was worth a try. My experiments led me to exposing the tick function inside whatever the "force" thing is, and then calling that in a blocking loop ~500 times after setting up the data and starting the "force" run. That seems to have done it. Primitive, but it works.
