### ISSUE TITLE
How to set the distance between two circle ?

### ISSUE THREAD

**Issue by cnhalo2** [fzaninotto/CodeFlower#7]
How to set the distance between two circle use Code Flower  ?

I want to set the svg full of the parent container, how ?

please email me :  huangyijie1989@gmail.com  

thanx!

**Comment by homlett** [comment]
In `CodeFlower.js`, you can play with the line 20 :
`.linkDistance(function(d) { return d.target._children ? 80 : 25; })`
Where 25 is the standard distance and 80 is the distance between two nodes when one is collapsed.
