### ISSUE TITLE
convertFromClocToJSON() doesn't work if cloc.exe executed with "--by-file-by-lang" flag

### ISSUE THREAD

**Issue by alundiak** [fzaninotto/CodeFlower#8]
I downloaded your dataConverter.js and I have used it in my code.
Everything works fine with 

```
cloc.exe --by-file  ....
```

but when I generate cloc file 

```
cloc.exe --by-file-by-lang ....
```

output cloc files can not be converted to JSON.

As result after cloc file is trying to be converted I have error 

```
Uncaught TypeError: Cannot set property 'name' of undefined dataConverter.js
```

in console in 32-33 this line:
https://github.com/fzaninotto/CodeFlower/blob/master/javascripts/dataConverter.js#L32

```
json = getChildren(json)[0];
json.name = 'root';
```

**Comment by fzaninotto** [comment]
That's because `by-file-by-lang` isn't supported. Use `--by-file` as explained in the doc.
